/**
 * Created by xinli on 2018/1/11.
 */

export const locales = [
  { key: 'zh_CN', value: '中文 (中国)' },
  { key: 'zh_TW', value: '中文 (台湾地区)' },
  { key: 'zh_HK', value: '中文 (香港)' },
  // { key: 'ar_AE', value: '阿拉伯文 (阿拉伯联合酋长国)' },
  // { key: 'ar_JO', value: '阿拉伯文 (约旦)' },
  // { key: 'ar_SY', value: '阿拉伯文 (叙利亚)' },
  // { key: 'hr_HR', value: '克罗地亚文 (克罗地亚)' },
  // { key: 'fr_BE', value: '法文 (比利时)' },
  // { key: 'es_PA', value: '西班牙文 (巴拿马)' },
  // { key: 'mt_MT', value: '马耳他文 (马耳他)' },
  // { key: 'es_VE', value: '西班牙文 (委内瑞拉)' },
  // { key: 'bg', value: '保加利亚文' },
  // { key: 'it', value: '意大利文' },
  // { key: 'ko', value: '朝鲜文' },
  // { key: 'uk', value: '乌克兰文' },
  // { key: 'lv', value: '拉托维亚文(列托)' },
  // { key: 'da_DK', value: '丹麦文 (丹麦)' },
  // { key: 'es_PR', value: '西班牙文 (波多黎哥)' },
  // { key: 'vi_VN', value: '越南文 (越南)' },
  { key: 'en_US', value: '英文 (美国)' },
  // { key: 'sr_ME', value: '塞尔维亚文 (黑山)' },
  // { key: 'sv_SE', value: '瑞典文 (瑞典)' },
  // { key: 'es_BO', value: '西班牙文 (玻利维亚)' },
  // { key: 'en_SG', value: '英文 (新加坡)' },
  // { key: 'ar_BH', value: '阿拉伯文 (巴林)' },
  // { key: 'pt', value: '葡萄牙文' },
  // { key: 'ar_SA', value: '阿拉伯文 (沙特阿拉伯)' },
  // { key: 'sk', value: '斯洛伐克文' },
  // { key: 'ar_YE', value: '阿拉伯文 (也门)' },
  // { key: 'hi_IN', value: '印地文 (印度)' },
  // { key: 'ga', value: '爱尔兰文' },
  // { key: 'en_MT', value: '英文 (马耳他)' },
  // { key: 'fi_FI', value: '芬兰文 (芬兰)' },
  // { key: 'et', value: '爱沙尼亚文' },
  // { key: 'sv', value: '瑞典文' },
  // { key: 'cs', value: '捷克文' },
  // { key: 'sr_BA_#Latn', value: '塞尔维亚文 (拉丁文,波斯尼亚和黑山共和国)' },
  // { key: 'el', value: '希腊文' },
  // { key: 'uk_UA', value: '乌克兰文 (乌克兰)' },
  // { key: 'hu', value: '匈牙利文' },
  // { key: 'fr_CH', value: '法文 (瑞士)' },
  // { key: 'in', value: '印度尼西亚文' },
  // { key: 'es_AR', value: '西班牙文 (阿根廷)' },
  // { key: 'ar_EG', value: '阿拉伯文 (埃及)' },
  // { key: 'ja_JP_JP_#u-ca-japanese', value: '日文 (日本,JP)' },
  // { key: 'es_SV', value: '西班牙文 (萨尔瓦多)' },
  // { key: 'pt_BR', value: '葡萄牙文 (巴西)' },
  // { key: 'be', value: '白俄罗斯文' },
  // { key: 'is_IS', value: '冰岛文 (冰岛)' },
  // { key: 'cs_CZ', value: '捷克文 (捷克共和国)' },
  // { key: 'es', value: '西班牙文' },
  // { key: 'pl_PL', value: '波兰文 (波兰)' },
  // { key: 'tr', value: '土耳其文' },
  // { key: 'ca_ES', value: '加泰罗尼亚文 (西班牙)' },
  // { key: 'sr_CS', value: '塞尔维亚文 (塞尔维亚及黑山)' },
  // { key: 'ms_MY', value: '马来文 (马来西亚)' },
  // { key: 'hr', value: '克罗地亚文' },
  // { key: 'lt', value: '立陶宛文' },
  // { key: 'es_ES', value: '西班牙文 (西班牙)' },
  // { key: 'es_CO', value: '西班牙文 (哥伦比亚)' },
  // { key: 'bg_BG', value: '保加利亚文 (保加利亚)' },
  // { key: 'sq', value: '阿尔巴尼亚文' },
  // { key: 'fr', value: '法文' },
  // { key: 'ja', value: '日文' },
  // { key: 'sr_BA', value: '塞尔维亚文 (波斯尼亚和黑山共和国)' },
  // { key: 'is', value: '冰岛文' },
  // { key: 'es_PY', value: '西班牙文 (巴拉圭)' },
  // { key: 'de', value: '德文' },
  // { key: 'es_EC', value: '西班牙文 (厄瓜多尔)' },
  // { key: 'es_US', value: '西班牙文 (美国)' },
  // { key: 'ar_SD', value: '阿拉伯文 (苏丹)' },
  // { key: 'en', value: '英文' },
  // { key: 'ro_RO', value: '罗马尼亚文 (罗马尼亚)' },
  // { key: 'en_PH', value: '英文 (菲律宾)' },
  // { key: 'ca', value: '加泰罗尼亚文' },
  // { key: 'ar_TN', value: '阿拉伯文 (突尼斯)' },
  // { key: 'sr_ME_#Latn', value: '塞尔维亚文 (拉丁文,黑山)' },
  // { key: 'es_GT', value: '西班牙文 (危地马拉)' },
  // { key: 'sl', value: '斯洛文尼亚文' },
  // { key: 'ko_KR', value: '朝鲜文 (韩国)' },
  // { key: 'el_CY', value: '希腊文 (塞浦路斯)' },
  // { key: 'es_MX', value: '西班牙文 (墨西哥)' },
  // { key: 'ru_RU', value: '俄文 (俄罗斯)' },
  // { key: 'es_HN', value: '西班牙文 (洪都拉斯)' },
  // { key: 'no_NO_NY', value: '挪威文 (挪威,Nynorsk)' },
  // { key: 'hu_HU', value: '匈牙利文 (匈牙利)' },
  // { key: 'th_TH', value: '泰文 (泰国)' },
  // { key: 'ar_IQ', value: '阿拉伯文 (伊拉克)' },
  // { key: 'es_CL', value: '西班牙文 (智利)' },
  // { key: 'fi', value: '芬兰文' },
  // { key: 'ar_MA', value: '阿拉伯文 (摩洛哥)' },
  // { key: 'ga_IE', value: '爱尔兰文 (爱尔兰)' },
  // { key: 'mk', value: '马其顿文' },
  // { key: 'tr_TR', value: '土耳其文 (土耳其)' },
  // { key: 'et_EE', value: '爱沙尼亚文 (爱沙尼亚)' },
  // { key: 'ar_QA', value: '阿拉伯文 (卡塔尔)' },
  // { key: 'sr__#Latn', value: '塞尔维亚文 (拉丁文)' },
  // { key: 'pt_PT', value: '葡萄牙文 (葡萄牙)' },
  // { key: 'fr_LU', value: '法文 (卢森堡)' },
  // { key: 'ar_OM', value: '阿拉伯文 (阿曼)' },
  // { key: 'th', value: '泰文' },
  // { key: 'sq_AL', value: '阿尔巴尼亚文 (阿尔巴尼亚)' },
  // { key: 'es_DO', value: '西班牙文 (多米尼加共和国)' },
  // { key: 'es_CU', value: '西班牙文 (古巴)' },
  // { key: 'ar', value: '阿拉伯文' },
  // { key: 'ru', value: '俄文' },
  // { key: 'en_NZ', value: '英文 (新西兰)' },
  // { key: 'sr_RS', value: '塞尔维亚文 (塞尔维亚)' },
  // { key: 'de_CH', value: '德文 (瑞士)' },
  // { key: 'es_UY', value: '西班牙文 (乌拉圭)' },
  // { key: 'ms', value: '马来文' },
  // { key: 'el_GR', value: '希腊文 (希腊)' },
  // { key: 'iw_IL', value: '希伯来文 (以色列)' },
  // { key: 'en_ZA', value: '英文 (南非)' },
  // { key: 'th_TH_TH_#u-nu-thai', value: '泰文 (泰国,TH)' },
  // { key: 'hi', value: '印地文' },
  // { key: 'fr_FR', value: '法文 (法国)' },
  // { key: 'de_AT', value: '德文 (奥地利)' },
  // { key: 'nl', value: '荷兰文' },
  // { key: 'no_NO', value: '挪威文 (挪威)' },
  // { key: 'en_AU', value: '英文 (澳大利亚)' },
  // { key: 'vi', value: '越南文' },
  // { key: 'nl_NL', value: '荷兰文 (荷兰)' },
  // { key: 'fr_CA', value: '法文 (加拿大)' },
  // { key: 'lv_LV', value: '拉托维亚文(列托) (拉脱维亚)' },
  // { key: 'de_LU', value: '德文 (卢森堡)' },
  // { key: 'es_CR', value: '西班牙文 (哥斯达黎加)' },
  // { key: 'ar_KW', value: '阿拉伯文 (科威特)' },
  // { key: 'sr', value: '塞尔维亚文' },
  // { key: 'ar_LY', value: '阿拉伯文 (利比亚)' },
  // { key: 'mt', value: '马耳他文' },
  // { key: 'it_CH', value: '意大利文 (瑞士)' },
  // { key: 'da', value: '丹麦文' },
  // { key: 'de_DE', value: '德文 (德国)' },
  // { key: 'ar_DZ', value: '阿拉伯文 (阿尔及利亚)' },
  // { key: 'sk_SK', value: '斯洛伐克文 (斯洛伐克)' },
  // { key: 'lt_LT', value: '立陶宛文 (立陶宛)' },
  // { key: 'it_IT', value: '意大利文 (意大利)' },
  // { key: 'en_IE', value: '英文 (爱尔兰)' },
  // { key: 'zh_SG', value: '中文 (新加坡)' },
  // { key: 'ro', value: '罗马尼亚文' },
  // { key: 'en_CA', value: '英文 (加拿大)' },
  // { key: 'nl_BE', value: '荷兰文 (比利时)' },
  // { key: 'no', value: '挪威文' },
  // { key: 'pl', value: '波兰文' },
  // { key: 'ja_JP', value: '日文 (日本)' },
  // { key: 'de_GR', value: '德文 (希腊)' },
  // { key: 'sr_RS_#Latn', value: '塞尔维亚文 (拉丁文,塞尔维亚)' },
  // { key: 'iw', value: '希伯来文' },
  // { key: 'en_IN', value: '英文 (印度)' },
  // { key: 'ar_LB', value: '阿拉伯文 (黎巴嫩)' },
  // { key: 'es_NI', value: '西班牙文 (尼加拉瓜)' },
  // { key: 'zh', value: '中文' },
  // { key: 'mk_MK', value: '马其顿文 (马其顿王国)' },
  // { key: 'be_BY', value: '白俄罗斯文 (白俄罗斯)' },
  // { key: 'sl_SI', value: '斯洛文尼亚文 (斯洛文尼亚)' },
  // { key: 'es_PE', value: '西班牙文 (秘鲁)' },
  // { key: 'in_ID', value: '印度尼西亚文 (印度尼西亚)' },
  // { key: 'en_GB', value: '英文 (英国)' },
];
